£!/bin/sh

for i in 1 .. 50
do
        qsub -q hp-sl.q -b y -wd ~/CUDA-Hashtable ./module_load.sh
        qstat
        sleep 1m
        qstat
        ls -l
        echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
done
